(WIP) feat: add zh-tw translation
wisp-forest/accessories pull request #155
Opened 2024-11-12 03:43 UTC by EvanHsieh0415

2024-11-12 08:19 UTC, notlin4 requested changes

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.group_filter.label": "群組過濾器：",
```suggestion
  "accessories.group_filter.label": "群組篩選器：",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.group_filter.toggle.enabled.tooltip": "隱藏群組過濾器按鈕",
```suggestion
  "accessories.group_filter.toggle.enabled.tooltip": "隱藏群組篩選器按鈕",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.group_filter.toggle.disabled.tooltip": "顯示群組過濾器按鈕",
```suggestion
  "accessories.group_filter.toggle.disabled.tooltip": "顯示群組篩選器按鈕",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.reset.group_filter": "重設群組過濾器",
```suggestion
  "accessories.reset.group_filter": "重設群組篩選器",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.screenOptions.allowSlotScrolling": "允許欄位介面滾動",
```suggestion
  "text.config.accessories.option.screenOptions.allowSlotScrolling": "允許欄位介面捲動",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "如果有模組會影響滾動時的物品操作，會在瀏覽飾品時出現問題，則可以關閉此選項以解決問題。"
```suggestion
    "如果有模組會影響捲動時的物品操作，會在瀏覽飾品時發生問題，則可以關閉此選項以解決問題。"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    " 滾動"
```suggestion
    " 捲動"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.widget_type.scrollable.tooltip": "可滾動的飾品布局",
```suggestion
  "accessories.widget_type.scrollable.tooltip": "可捲動的飾品佈局",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    " 禁用"
```suggestion
    " 停用"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.unique_slots.toggle.hide": "隱藏獨特槽位",
```suggestion
  "accessories.unique_slots.toggle.show": "顯示獨特欄位",
  "accessories.unique_slots.toggle.hide": "隱藏獨特欄位",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.category.clientOptions": "客戶端選項",
```suggestion
  "text.config.accessories.category.clientOptions": "用戶端選項",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "包含用於渲染或玩家輸入的更通用的客戶端選項"
```suggestion
    "包含更多通用的用戶端選項，用於繪製或玩家輸入"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.clientOptions.forceNullRenderReplacement": "強制空渲染替換",
```suggestion
  "text.config.accessories.option.clientOptions.forceNullRenderReplacement": "強制空繪製替換",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "強制任何已註冊的渲染，若發現沒有渲染，就改用預設渲染。"
```suggestion
    "強制任何已登錄的繪製，若發現沒有繪製，就改用預設繪製。"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "停用在打開飾品介面且未找到使用過的飾品欄時所顯示的錯誤訊息。"
```suggestion
    "停用在開啟飾品介面且未找到使用過的飾品欄時顯示的錯誤訊息。"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.clientOptions.showCosmeticAccessories": "顯示物品外觀渲染",
```suggestion
  "text.config.accessories.option.clientOptions.showCosmeticAccessories": "顯示物品外觀繪製",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "啟用/停用外觀物品變體（如果已裝備）的渲染。"
```suggestion
    "啟用/停用外觀物品變體（如果已裝備）的繪製。"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.clientOptions.disabledDefaultRenders": "停用預設渲染",
```suggestion
  "text.config.accessories.option.clientOptions.disabledDefaultRenders": "停用預設繪製",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.enum.playerEquipControl.disabled": "禁用",
```suggestion
  "text.config.accessories.enum.playerEquipControl.disabled": "停用",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "當游標懸停在物品上時的渲染效果"
```suggestion
    "當游標懸停在物品上時的繪製效果"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.disabledDefaultRenders": "禁用預設渲染器",
```suggestion
  "text.config.accessories.option.disabledDefaultRenders": "停用預設渲染器",
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "停用指定飾品欄位的預設渲染，例如方塊或/和物品的渲染"
```suggestion
    "停用指定飾品欄位的預設繪製，例如方塊或/和物品的繪製"
```

2024-11-12 08:19 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "accessories.slot.accessories.head": "頭盔",
```suggestion
  "accessories.slot.accessories.head": "頭部",
```

2024-11-12 11:27 UTC, EvanHsieh0415 commented
review done

2024-11-12 14:53 UTC, notlin4 requested changes

2024-11-12 14:53 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "如果正在使用，停用內建的預設渲染器渲染物品。"
```suggestion
    "如果正在使用，停用內建的預設渲染器繪製物品。"
```

2024-11-12 14:53 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "啟用時使背包中的實體模型看向滑鼠游標，反之當禁用時則允許手動旋轉實體模型。"
```suggestion
    "啟用時使背包中的實體模型看向滑鼠游標，反之當停用時則允許手動旋轉實體模型。"
```

2024-11-12 14:53 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +    "游標未懸停在物品上的渲染效果"
```suggestion
    "游標未懸停在物品上的繪製效果"
```

2024-11-12 14:53 UTC, notlin4 commented on common/src/main/resources/assets/accessories/lang/zh_tw.json
> +  "text.config.accessories.option.screenOptions.unHoveredOptions.renderUnHovered": "依然渲染未有游標懸停的物品",
```suggestion
  "text.config.accessories.option.screenOptions.unHoveredOptions.renderUnHovered": "依然繪製未有游標懸停的物品",
```

2024-12-16 00:22 UTC, Dragon-Seeker commented
Is this PR ready to be pulled in or is there any more edits that need to be done?

2024-12-16 00:39 UTC, EvanHsieh0415 commented
> Is this PR ready to be pulled in or is there any more edits that need to be done?

Looks like the revisions are done and ready to be pulled.

2024-12-16 20:58 UTC, merged